### PR TITLE
Local project editable installs

### LINKED ISSUE #42: resource, understand, and solve the edit-able local install question
Convert VoteTrackerPlus to use Python local project installs. This resolves subtle path issues with imports and access to scripts by making them behave the same as if the package had been installed using Pip.

Git is still required to use VTP, but editable installs allow Git to track changes to sources while still using standard Python packaging.

Steps:

- [x] Test using _local editable installs_:
  - [x] For Poetry:
    - [x] Set up `pyproject.toml` to use Poetry as the `build-system`.
    - [x] Specify requirements in `pyproject.toml`
    - [x] Lock the dependencies in `poetry.lock`
    - [x] Add scripts to `tools.poetry.scripts` in `pyproject.toml`
    - [x] Create a virtual environment: `poetry shell` or `poetry install`
    - [x] Perform an editable install: `poetry install`
    - [x] Ensure absolute import paths work
          This means: `from vtp.utils import ...` 
    - [x] Ensure editable source installs that are tracked by Git
  - [x] For Pip + Setuptools:
    - [x] Modify `pyproject.toml` to use `setuptools` as the `build-system`
    - [x] Specify the requirements in `setup.cfg`
    - [x] Add scripts to `tools.poetry.scripts` in `pyproject.toml`
    - [x] Create a virtual environment: `python -m virtualenv`
    - [x] Perform an editable install: `pip install -e .`
    - [x] Ensure absolute import paths work
          This means: `from vtp.utils import ...` 
    - [x] Ensure editable source installs that are tracked by Git
  - ~For Conda~: Deferring on this as its not quite the same as the other two and it's harder for me to test.
- [ ] Test using _regular installs_.
      Note that this means imports work and scripts run. But the scripts will fail if there's no Git repository in the install.

Original post:

> We should figure out the right/better way to deal with distributing the VTP scripts and libraries.
> 
> The original way is to just include the code with the election configuration (currently the mock demo repo) and ballot CVR's effectively all in the same Merkle tree by virtue of git submodules.
> 
> The potential better way is to support an edit-able install across at least poetry and conda.
> At some point the requirement/criteria for 'better' should be listed and agreed too.  However, it seems that some research and perhaps a working example may help regarding the criteria for 'better'.

### PR DESCRIPTION
**Pull request by ion-oset**
Local project editable installs using Poetry, Setuptools (modern), and Setuptools (legacy).

See the file `_tools/build/README-build.md` for details on how to use.

_Fixes_: #42.

_Note_: I've deferred on renaming the packages as [discussed in the issue](https://github.com/TrustTheVote-Project/VoteTrackerPlus/issues/42#issuecomment-1302449185), until the rest is reviewed and accepted.

### CODE REVIEW

**Comment by windoverwater** [comment]
@ion-oset - this looks great!  Will start testing but in parallel wanted to say that the only initial comments are to rename README-build.md to README.md and the addition of (manual) section numbers to the README markdown.  I am happy to do both post the merge (from the fork).  Thanks!

**Review by windoverwater — APPROVED** [review]
Actually, in testing this, I just want to keep going and build on this (as there are issues that I want to address that are not directly associated with this change).  So if it is ok with you, I am just going to approve it as is.

**Comment by windoverwater** [comment]
p.s. only that commit is signed by you - can you sign the other ones?

**Comment by ion-oset** [comment]
I rebased and signed all the commits and force pushed. GitHub is still listing them as unverified though and I can't figure out why. Clicking on any "UNVERIFIED" badge in the [commit listing](https://github.com/TrustTheVote-Project/VoteTrackerPlus/pull/44/commits) tells me:

> No user is associated with the committer email. 

However the GPG key in GitHub is associated with the name and email in the commits. If you look locally at the branch with `git log --show-signatures` it shows that they are all signed with the (sub)key whose signature is `EFE04F5C` and that's the key GitHub knows about. I have no reason to think GitHub doesn't know about subkeys.

I'm not sure what's going on here.

**Comment by windoverwater** [comment]
FWIIW I have already modified the Makefile in an incompatible manner based on the commit prior to that.  But I am going to approve/merge this anyway and resolve the conflict in another branch.

**Review by windoverwater — DISMISSED** [review]

**Comment by windoverwater** [comment]
FYI - there is still a change that is not signed - it looks like it is this one: https://github.com/ion-oset/vote-tracker-plus/commit/7822e5674b45a60257fd52d9d4b1817a41366d85

Can you sign that one?  Actually, removing it also works as that is the change that conflicts with my branch, so if you want to remove it that is also fine.

**Review by windoverwater — APPROVED** [review]

**Comment by windoverwater** [comment]
FYI - I squash merged this branch and pushed it to master and it went in fine.  No clue why it worked as I thought it would not.  But in any case, I am going to close this PR as it is in.

**Pull request closed without merging**
